config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'


  root to: 'pages#one' #seteo pagina de inicio
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def one
    end

    def two
    end

    def three
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar-inverse">
      <a class="navbar-brand" href="<%= root_path %>">Page One</a>
      <a class="navbar-brand" href="<%= pages_two_path %>">Page two</a>
      <a class="navbar-brand" href="<%= pages_three_path %>">Page three</a>
    </nav>





    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1> Camilo Ignacio Monsalve Silva</h1>

app/views/pages/three.html.erb
<h2>I'm a title</title></h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At accusantium totam nesciunt suscipit cumque molestias, cupiditate natus blanditiis quos ad quod optio ratione illum, omnis minima veniam magnam, a ea!</p>

app/views/pages/two.html.erb
<%= image_tag "rake_routes.png" %>